#ifndef    CUDA_WRAPPER_HXX
# define   CUDA_WRAPPER_HXX

# include "CudaWrapper.cuh"

namespace utils {

  inline
  CudaWrapper::~CudaWrapper() {}

  inline
  bool
  CudaWrapper::check(cuda::stream_t stream) {
    // We actually don't really need the input stream, we will just peek at the
    // error generated by any API call and return `true` if there are some.
    return isError(cudaPeekAtLastError());
  }

  inline
  std::string
  CudaWrapper::getLastError() {
    Guard guard(m_propsLocker);

    std::string err;
    err.swap(m_lastError);

    return err;
  }

  inline
  bool
  CudaWrapper::isError(cudaError_t error) {
    return error != cudaSuccess;
  }

}

#endif    /* CUDA_WRAPPER_HXX */